project_id = "pyscczcuersdjvpmkiec"

[functions.webhook-receiver]
verify_jwt = false

[functions.generate-ai-report]
verify_jwt = true

[functions.ai-analytics-chat]
verify_jwt = true

[functions.create-test-user]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.weekly-report]
verify_jwt = false

[functions.crm-automation]
verify_jwt = true

[functions.generate-ad-copy]
verify_jwt = true

[functions.check-integrations]
verify_jwt = false

[functions.check-db]
enabled = true
verify_jwt = true
import_map = "./functions/check-db/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/check-db/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/check-db/*.html" ]
