import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export interface AIRopTask {
  id: string;
  project_id: string;
  prompt: string;
  status: 'pending' | 'in_progress' | 'processing' | 'completed' | 'error';
  response: string | null;
  error_message: string | null;
  created_at: string;
  completed_at?: string | null;
  execution_logs?: string[];
}

export interface AIRopAudit {
  id: string;
  project_id: string;
  audit_date: string;
  overall_score: number;
  critical_errors: string[];
  growth_points: string[];
  bot_stats: {
    total_dialogs?: number;
    logic_errors?: number;
    successful_bookings?: number;
  };
  summary: string | null;
  created_at: string;
}

export const useAIRop = (projectId: string | null) => {
  const [tasks, setTasks] = useState<AIRopTask[]>([]);
  const [audits, setAudits] = useState<AIRopAudit[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);

  const fetchTasks = useCallback(async () => {
    if (!projectId) return;
    const { data, error } = await supabase
      .from('ai_bridge_tasks')
      .select('*')
      .eq('project_id', projectId)
      .order('created_at', { ascending: false })
      .limit(20);

    if (error) {
      console.error('Error fetching tasks:', error);
      return;
    }

    setTasks(data as AIRopTask[]);
  }, [projectId]);

  const fetchAudits = useCallback(async () => {
    if (!projectId) return;
    // Keep reading audits from ai_rop_audits for now as they might be generated by the tasks
    const { data, error } = await supabase
      .from('ai_rop_audits')
      .select('*')
      .eq('project_id', projectId)
      .order('audit_date', { ascending: false })
      .limit(10);

    if (error) {
      console.error('Error fetching audits:', error);
      return;
    }

    // Parse JSONB fields
    const parsedAudits = data.map(audit => ({
      ...audit,
      critical_errors: Array.isArray(audit.critical_errors) ? audit.critical_errors : [],
      growth_points: Array.isArray(audit.growth_points) ? audit.growth_points : [],
      bot_stats: typeof audit.bot_stats === 'object' ? audit.bot_stats : {}
    })) as AIRopAudit[];

    setAudits(parsedAudits);
  }, [projectId]);

  const createTask = useCallback(async (taskText: string) => {
    if (!taskText.trim()) return null;
    if (!projectId) {
      toast.error('Сначала выберите проект');
      return null;
    }
    
    setSubmitting(true);
    
    // We don't need created_by for bridge tasks usually, or it's not in schema
    // Schema: id, project_id, prompt, status, response, execution_logs, created_at
    
    const { data, error } = await supabase
      .from('ai_bridge_tasks')
      .insert({
        project_id: projectId,
        prompt: taskText.trim(),
        status: 'pending'
      })
      .select()
      .single();

    setSubmitting(false);

    if (error) {
      console.error('Error creating task:', error);
      toast.error('Ошибка создания задачи');
      return null;
    }

    toast.success('Задача отправлена в AI Bridge');
    return data as AIRopTask;
  }, [projectId]);

  // Initial load
  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      if (!projectId) {
        setTasks([]);
        setAudits([]);
        setLoading(false);
        return;
      }
      await Promise.all([fetchTasks(), fetchAudits()]);
      setLoading(false);
    };
    
    loadData();
  }, [projectId, fetchTasks, fetchAudits]);

  // Realtime subscription for tasks
  useEffect(() => {
    if (!projectId) return;
    const channel = supabase
      .channel('ai-bridge-tasks-rop')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'ai_bridge_tasks',
          filter: `project_id=eq.${projectId}`
        },
        (payload) => {
          if (payload.eventType === 'INSERT') {
            setTasks(prev => [payload.new as AIRopTask, ...prev]);
          } else if (payload.eventType === 'UPDATE') {
            setTasks(prev => 
              prev.map(task => 
                task.id === payload.new.id ? payload.new as AIRopTask : task
              )
            );
            
            // Notify when task completed
            if (payload.new.status === 'completed') {
              // toast.success('ИИ-РОП завершил задачу'); // Optional: might be too noisy if chat is active
            }
          } else if (payload.eventType === 'DELETE') {
            setTasks(prev => prev.filter(task => task.id !== payload.old.id));
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [projectId]);

  return {
    tasks,
    audits,
    loading,
    submitting,
    createTask,
    refetch: () => Promise.all([fetchTasks(), fetchAudits()])
  };
};
